//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L5K_Compiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L5K_Compiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;(*********************************************
        ///
        ///  Import-Export
        ///  Version   := RSLogix 5000 v27.00
        ///  Owner     := Gyptech, Gyptech
        ///  Exported  := Sat Jan 1 00:00:00 2000
        ///
        ///  Note:  File encoded in UTF-8.  Only edit file in a program 
        ///         which supports UTF-8 (like Notepad, not Wordpad).
        ///
        ///**********************************************)
        ///IE_VER := @IEVER@;
        ///
        ///CONTROLLER PRCJ_Generic (ProcessorType := &quot;&quot;@PROCTYPE@&quot;&quot;,
        ///                         Major := 27,
        ///                         TimeSlice :=  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE 1734_AENTR_@AENTRNUM@ (Parent := &quot;&quot;ETHERNET_@ETHERNUM@&quot;&quot;,
        ///	              ParentModPortId := 2,
        ///	              CatalogNumber := &quot;&quot;1734-AENTR/A&quot;&quot;,
        ///	              Vendor := 1,
        ///	              ProductType := 12,
        ///	              ProductCode := 196,
        ///	              Major := 3,
        ///	              Minor := 1,
        ///	              PortLabel := &quot;&quot;ENet&quot;&quot;,
        ///	              ChassisSize := @SIZE@,
        ///	              Slot := @SLOT@,
        ///	              NodeAddress := &quot;&quot;192.168.0.1&quot;&quot;,
        ///	              CommMethod := 805306369,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734AENTR {
            get {
                return ResourceManager.GetString("m1734AENTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE $NoName (Parent := &quot;&quot;1734_AENTR_@AENTRNUM@&quot;&quot;,
        ///	            CatalogNumber := &quot;&quot;1734-IB4D/C&quot;&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 7,
        ///	            ProductCode := 307,
        ///	            Major := 3,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	            Slot := @SLOT@,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModule := 0,
        ///	            KeyMask := 2#0000_0000_0000_0000)
        ///			ExtendedProp := [[[___&lt;public&gt;&lt;ConfigID&gt;262145&lt;/ConfigI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734IB4D {
            get {
                return ResourceManager.GetString("m1734IB4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE $NoName (Parent := &quot;&quot;1734_AENTR_@AENTRNUM@&quot;&quot;,
        ///	            ParentModPortId := 1,
        ///	            CatalogNumber := &quot;&quot;1734-IB8S/A&quot;&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 35,
        ///	            ProductCode := 15,
        ///	            Major := 1,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	            Slot := @SLOT@,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModule := 1,
        ///	            KeyMask := 2#0000_0000_0001_1111,
        ///	            SafetyNet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734IB8S {
            get {
                return ResourceManager.GetString("m1734IB8S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE $NoName (Parent := &quot;&quot;1734_AENTR_@AENTRNUM@&quot;&quot;,
        ///	            ParentModPortId := 1,
        ///	            CatalogNumber := &quot;&quot;1734-IE2C/C&quot;&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 115,
        ///	            ProductCode := 24,
        ///	            Major := 3,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	            Slot := @SLOT@,
        ///	            CommMethod := 536870913,
        ///	            ConfigMethod := 8388609,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734IE2C {
            get {
                return ResourceManager.GetString("m1734IE2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE $NoName (Parent := &quot;&quot;1734_AENTR_@AENTRNUM@&quot;&quot;,
        ///	                 ParentModPortId := 1,
        ///	                 CatalogNumber := &quot;&quot;1734-IR2/C&quot;&quot;,
        ///	                 Vendor := 1,
        ///	                 ProductType := 115,
        ///	                 ProductCode := 50,
        ///	                 Major := 3,
        ///	                 Minor := 1,
        ///	                 PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	                 Slot := @SLOT@,
        ///	                 CommMethod := 536870913,
        ///	                 ConfigMethod := 8388609,
        ///	                 M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734IR2 {
            get {
                return ResourceManager.GetString("m1734IR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE $NoName (Parent := &quot;&quot;1734_AENTR_@AENTRNUM@&quot;&quot;,
        ///	            ParentModPortId := 1,
        ///	            CatalogNumber := &quot;&quot;1734-OB4E/C&quot;&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 7,
        ///	            ProductCode := 134,
        ///	            Major := 3,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	            Slot :=@SLOT@,
        ///	            CommMethod := 1073741824,
        ///	            ConfigMethod := 8388611,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModule [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734OB4E {
            get {
                return ResourceManager.GetString("m1734OB4E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE $NoName (Parent := &quot;&quot;1734_AENTR_@AENTRNUM@&quot;&quot;,
        ///	            ParentModPortId := 1,
        ///	            CatalogNumber := &quot;&quot;1734-OB8S/A&quot;&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 35,
        ///	            ProductCode := 16,
        ///	            Major := 1,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	            Slot := @SLOT@,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModule := 1,
        ///	            KeyMask := 2#0000_0000_0001_1111,
        ///	            SafetyNet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734OB8S {
            get {
                return ResourceManager.GetString("m1734OB8S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE $NoName (Parent := &quot;&quot;1734_AENTR_@AENTRNUM@&quot;&quot;,
        ///	            ParentModPortId := 1,
        ///	            CatalogNumber := &quot;&quot;1734-OE2C/C&quot;&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 115,
        ///	            ProductCode := 25,
        ///	            Major := 3,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	            Slot := @SLOT@,
        ///	            CommMethod := 536870913,
        ///	            ConfigMethod := 8388609,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734OE2C {
            get {
                return ResourceManager.GetString("m1734OE2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE Local (Parent := &quot;&quot;Local&quot;&quot;,
        ///	              ParentModPortId := 1,
        ///	              CatalogNumber := &quot;&quot;1756-L72S&quot;&quot;,
        ///	              Vendor := 1,
        ///	              ProductType := 14,
        ///	              ProductCode := 147,
        ///	              Major := 27,
        ///	              Minor := 11,
        ///	              PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	              ChassisSize := 13,
        ///	              Slot := @SLOT@,
        ///	              Mode := 2#0000_0000_0000_0001,
        ///	              CompatibleModule := 0,
        ///	              KeyMask := 2#00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1752L72S {
            get {
                return ResourceManager.GetString("m1752L72S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE ETHERNET_@ETHERNUM@ (Description := &quot;&quot;&quot;&quot;,
        ///	               Parent := &quot;&quot;Local&quot;&quot;,
        ///	               ParentModPortId := 1,
        ///	               CatalogNumber := &quot;&quot;1756-EN2T&quot;&quot;,
        ///	               Vendor := 1,
        ///	               ProductType := 12,
        ///	               ProductCode := 166,
        ///	               Major := 10,
        ///	               Minor := 1,
        ///	               PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	               Slot := @SLOT@,
        ///	               NodeAddress := &quot;&quot;192.168.0.1&quot;&quot;,
        ///	               Mode := 2#0000_0000_0000_0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1756EN2T {
            get {
                return ResourceManager.GetString("m1756EN2T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE Local (Parent := &quot;&quot;Local&quot;&quot;,
        ///	              ParentModPortId := 1,
        ///	              CatalogNumber := &quot;&quot;1756-L71S&quot;&quot;,
        ///	              Vendor := 1,
        ///	              ProductType := 14,
        ///	              ProductCode := 158,
        ///	              Major := 27,
        ///	              Minor := 11,
        ///	              PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	              ChassisSize := 13,
        ///	              Slot := @SLOT@,
        ///	              Mode := 2#0000_0000_0000_0001,
        ///	              CompatibleModule := 0,
        ///	              KeyMask := 2#00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1756L71S {
            get {
                return ResourceManager.GetString("m1756L71S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE USPC_ZZ:Partner (Parent := &quot;&quot;Comms_Pxxxx&quot;&quot;,
        ///	                        ParentModPortId := 1,
        ///	                        CatalogNumber := &quot;&quot;1756-L7SP&quot;&quot;,
        ///	                        Vendor := 1,
        ///	                        ProductType := 14,
        ///	                        ProductCode := 146,
        ///	                        Major := 24,
        ///	                        Minor := 1,
        ///	                        PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	                        Slot := 12,
        ///	                        Mode := 2#0000_0000_0000_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1756L7SP {
            get {
                return ResourceManager.GetString("m1756L7SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE _xxxx_01M02 (Description := &quot;&quot;VFD Speed Control&quot;&quot;,
        ///	                    Parent := &quot;&quot;Drives&quot;&quot;,
        ///	                    ParentModPortId := 2,
        ///	                    CatalogNumber := &quot;&quot;PowerFlex 753-ENETR&quot;&quot;,
        ///	                    Vendor := 1,
        ///	                    ProductType := 142,
        ///	                    ProductCode := 1168,
        ///	                    Major := 11,
        ///	                    Minor := 2,
        ///	                    PortLabel := &quot;&quot;ENet&quot;&quot;,
        ///	                    Slot := 0,
        ///	                    NodeAddres [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mPowerFlex753ENETR {
            get {
                return ResourceManager.GetString("mPowerFlex753ENETR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE _xxxx_01M05 (Description := &quot;&quot;CIP Control&quot;&quot;,
        ///
        ///                        Parent := &quot;&quot;Drives&quot;&quot;,
        ///	                    ParentModPortId := 2,
        ///	                    Vendor := 1,
        ///	                    ProductType := 37,
        ///	                    ProductCode := 1,
        ///	                    Major := 3,
        ///	                    Minor := 1,
        ///	                    PortLabel := &quot;&quot;ENet&quot;&quot;,
        ///	                    NodeAddress := &quot;&quot;192.168.0.5&quot;&quot;,
        ///	                    Mode := 2#0000_0000_0000_0000,
        ///	                    Compat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mPowerFlex755 {
            get {
                return ResourceManager.GetString("mPowerFlex755", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;	MODULE _xxxx_xxMxx (Description := &quot;&quot;FS Length Adj LH&quot;&quot;,
        ///
        ///                        Parent := &quot;&quot;Drives&quot;&quot;,
        ///	                    ParentModPortId := 2,
        ///	                    CatalogNumber := &quot;&quot;PowerFlex 755-EENET-CM&quot;&quot;,
        ///	                    Vendor := 1,
        ///	                    ProductType := 37,
        ///	                    ProductCode := 21,
        ///	                    Major := 11,
        ///	                    Minor := 2,
        ///	                    PortLabel := &quot;&quot;ENet&quot;&quot;,
        ///	                    NodeAddress := &quot;&quot;192.168.70.101&quot;&quot;,
        ///	   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mPowerFlex755EENETCM {
            get {
                return ResourceManager.GetString("mPowerFlex755EENETCM", resourceCulture);
            }
        }
    }
}
