//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L5K_Compiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L5K_Compiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_40x {
            get {
                object obj = ResourceManager.GetObject("add_40x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_40x {
            get {
                object obj = ResourceManager.GetObject("delete_40x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*********************************************
        ///
        ///  Import-Export
        ///  Version   := RSLogix 5000 v27.00
        ///  Owner     := Gyptech, Gyptech
        ///  Exported  := Sat Jan 1 00:00:00 2000
        ///
        ///  Note:  File encoded in UTF-8.  Only edit file in a program 
        ///         which supports UTF-8 (like Notepad, not Wordpad).
        ///
        ///**********************************************)
        ///IE_VER := @IEVER@;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highlight_40x {
            get {
                object obj = ResourceManager.GetObject("highlight_40x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MODULE @NAME@ (Description := &quot;@DESC@&quot;,
        ///	              Parent := &quot;@PARENT@&quot;,
        ///	              ParentModPortId := 2,
        ///	              CatalogNumber := &quot;1734-AENTR/A&quot;,
        ///	              Vendor := 1,
        ///	              ProductType := 12,
        ///	              ProductCode := 196,
        ///	              Major := 3,
        ///	              Minor := 1,
        ///	              PortLabel := &quot;ENet&quot;,
        ///	              ChassisSize := @SIZE@,
        ///	              Slot := @SLOT@,
        ///	              NodeAddress := &quot;@IP@&quot;,
        ///	              CommMethod := 805306369,
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734AENTR {
            get {
                return ResourceManager.GetString("m1734AENTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MODULE @NAME@ (Parent := &quot;@PARENT@&quot;,
        ///	            CatalogNumber := &quot;1734-IB4D/C&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 7,
        ///	            ProductCode := 307,
        ///	            Major := 3,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;RxBACKPLANE&quot;,
        ///	            Slot := @SLOT@,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModule := 0,
        ///	            KeyMask := 2#0000_0000_0000_0000)
        ///			ExtendedProp := [[[___&lt;public&gt;&lt;ConfigID&gt;262145&lt;/ConfigID&gt;&lt;/public&gt;___]]]
        ///
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734IB4D {
            get {
                return ResourceManager.GetString("m1734IB4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MODULE @NAME@ (Parent := &quot;@PARENT@&quot;,
        ///	            ParentModPortId := 1,
        ///	            CatalogNumber := &quot;1734-IB8S/A&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 35,
        ///	            ProductCode := 15,
        ///	            Major := 1,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;RxBACKPLANE&quot;,
        ///	            Slot := @SLOT@,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModule := 1,
        ///	            KeyMask := 2#0000_0000_0001_1111,
        ///	            SafetyNetwork := 16#0000_3aeb_0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734IB8S {
            get {
                return ResourceManager.GetString("m1734IB8S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MODULE @NAME@ (Parent := &quot;@PARENT@&quot;,
        ///	            ParentModPortId := 1,
        ///	            CatalogNumber := &quot;1734-IE2C/C&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 115,
        ///	            ProductCode := 24,
        ///	            Major := 3,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;RxBACKPLANE&quot;,
        ///	            Slot := @SLOT@,
        ///	            CommMethod := 536870913,
        ///	            ConfigMethod := 8388609,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModule := 0,
        ///	             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734IE2C {
            get {
                return ResourceManager.GetString("m1734IE2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MODULE @NAME@ (Parent := &quot;@PARENT@&quot;,
        ///	                 ParentModPortId := 1,
        ///	                 CatalogNumber := &quot;1734-IR2/C&quot;,
        ///	                 Vendor := 1,
        ///	                 ProductType := 115,
        ///	                 ProductCode := 50,
        ///	                 Major := 3,
        ///	                 Minor := 1,
        ///	                 PortLabel := &quot;RxBACKPLANE&quot;,
        ///	                 Slot := @SLOT@,
        ///	                 CommMethod := 536870913,
        ///	                 ConfigMethod := 8388609,
        ///	                 Mode := 2#0000_0000_000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734IR2 {
            get {
                return ResourceManager.GetString("m1734IR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MODULE @NAME@ (Parent := &quot;@PARENT@&quot;,
        ///	            ParentModPortId := 1,
        ///	            CatalogNumber := &quot;1734-OB4E/C&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 7,
        ///	            ProductCode := 134,
        ///	            Major := 3,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;RxBACKPLANE&quot;,
        ///	            Slot :=@SLOT@,
        ///	            CommMethod := 1073741824,
        ///	            ConfigMethod := 8388611,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModule := 0,
        ///	            K [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734OB4E {
            get {
                return ResourceManager.GetString("m1734OB4E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODULE @NAME@ (Parent := &quot;@PARENT@&quot;,
        ///	            ParentModPortId := 1,
        ///	            CatalogNumber := &quot;1734-OB8E/C&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 7,
        ///	            ProductCode := 218,
        ///	            Major := 3,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;RxBACKPLANE&quot;,
        ///	            Slot := @SLOT@,
        ///	            CommMethod := 1073741824,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModule := 1,
        ///	            KeyMask := 2#0000_0000_0001_1111)
        ///			Ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734OB8E {
            get {
                return ResourceManager.GetString("m1734OB8E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MODULE @NAME@ (Parent := &quot;@PARENT@&quot;,
        ///	            ParentModPortId := 1,
        ///	            CatalogNumber := &quot;1734-OB8S/A&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 35,
        ///	            ProductCode := 16,
        ///	            Major := 1,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;&quot;RxBACKPLANE&quot;&quot;,
        ///	            Slot := @SLOT@,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModule := 1,
        ///	            KeyMask := 2#0000_0000_0001_1111,
        ///	            SafetyNetwork := 16#0000_3aeb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734OB8S {
            get {
                return ResourceManager.GetString("m1734OB8S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MODULE @NAME@ (Parent := &quot;@PARENT@&quot;,
        ///	            ParentModPortId := 1,
        ///	            CatalogNumber := &quot;1734-OE2C/C&quot;,
        ///	            Vendor := 1,
        ///	            ProductType := 115,
        ///	            ProductCode := 25,
        ///	            Major := 3,
        ///	            Minor := 1,
        ///	            PortLabel := &quot;RxBACKPLANE&quot;,
        ///	            Slot := @SLOT@,
        ///	            CommMethod := 536870913,
        ///	            ConfigMethod := 8388609,
        ///	            Mode := 2#0000_0000_0000_0000,
        ///	            CompatibleModule := 0,
        ///	             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1734OE2C {
            get {
                return ResourceManager.GetString("m1734OE2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MODULE @NAME@ (Parent := &quot;Local&quot;,
        ///	              ParentModPortId := 1,
        ///	              CatalogNumber := &quot;1756-L72S&quot;,
        ///	              Vendor := 1,
        ///	              ProductType := 14,
        ///	              ProductCode := 147,
        ///	              Major := 27,
        ///	              Minor := 11,
        ///	              PortLabel := &quot;RxBACKPLANE&quot;,
        ///	              ChassisSize := @SIZE@,
        ///	              Slot := @SLOT@,
        ///	              Mode := 2#0000_0000_0000_0001,
        ///	              CompatibleModule := 0,
        ///	              KeyMask := 2#0000_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1752L72S {
            get {
                return ResourceManager.GetString("m1752L72S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MODULE @NAME@ (Description := &quot;@DESC@&quot;,
        ///	               Parent := &quot;Local&quot;,
        ///	               ParentModPortId := 1,
        ///	               CatalogNumber := &quot;1756-EN2T&quot;,
        ///	               Vendor := 1,
        ///	               ProductType := 12,
        ///	               ProductCode := 166,
        ///	               Major := 10,
        ///	               Minor := 1,
        ///	               PortLabel := &quot;RxBACKPLANE&quot;,
        ///	               Slot := @SLOT@,
        ///	               NodeAddress := &quot;@IP@&quot;,
        ///	               Mode := 2#0000_0000_0000_0000,
        ///	               Comp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1756EN2T {
            get {
                return ResourceManager.GetString("m1756EN2T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROLLER @NAME@ (Description := &quot;@DESC@&quot;,
        ///                    ProcessorType := &quot;1756-L71S&quot;,
        ///                    Major := 27,
        ///                    TimeSlice := 20,
        ///                    ShareUnusedTimeSlice := 1,
        ///                    RedundancyEnabled := 0,
        ///                    KeepTestEditsOnSwitchOver := 0,
        ///                    DataTablePadPercentage := 50,
        ///                    SecurityCode := 0,
        ///                    ChangesToDetect := 16#ffff_ffff_ffff_ffff,
        ///                    SFCExecutionControl :=  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1756L71S {
            get {
                return ResourceManager.GetString("m1756L71S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROLLER @NAME@ (Description := &quot;@DESC@&quot;,
        ///                 ProcessorType := &quot;1756-L72S&quot;,
        ///                 Major := 28,
        ///                 TimeSlice := 20,
        ///                 ShareUnusedTimeSlice := 1,
        ///                 RedundancyEnabled := 0,
        ///                 KeepTestEditsOnSwitchOver := 0,
        ///                 DataTablePadPercentage := 50,
        ///                 SecurityCode := 0,
        ///                 ChangesToDetect := 16#ffff_ffff_ffff_ffff,
        ///                 SFCExecutionControl := &quot;CurrentActive&quot;,
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m1756L72S {
            get {
                return ResourceManager.GetString("m1756L72S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODULE @NAME@ (Description := &quot;@DESC@&quot;,
        ///	                  Parent := &quot;@PARENT@&quot;,
        ///	                  ParentModPortId := 2,
        ///	                  CatalogNumber := &quot;PowerFlex 525-EENET&quot;,
        ///	                  Vendor := 1,
        ///	                  ProductType := 150,
        ///	                  ProductCode := 9,
        ///	                  Major := 4,
        ///	                  Minor := 1,
        ///	                  PortLabel := &quot;ENet&quot;,
        ///	                  Slot := 0,
        ///	                  NodeAddress := &quot;@IP@&quot;,
        ///	                  CommMethod := 5368 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mPowerFlex525EENET {
            get {
                return ResourceManager.GetString("mPowerFlex525EENET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODULE @NAME@ (Description := &quot;@DESC@&quot;,
        ///	                    Parent := &quot;@PARENT@&quot;,
        ///	                    ParentModPortId := 2,
        ///	                    CatalogNumber := &quot;PowerFlex 753-ENETR&quot;,
        ///	                    Vendor := 1,
        ///	                    ProductType := 142,
        ///	                    ProductCode := 1168,
        ///	                    Major := 9,
        ///	                    Minor := 1,
        ///	                    PortLabel := &quot;ENet&quot;,
        ///	                    Slot := 0,
        ///	                    NodeAddress := &quot;@IP@&quot;,
        ///	            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mPowerFlex753ENETR {
            get {
                return ResourceManager.GetString("mPowerFlex753ENETR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_40x {
            get {
                object obj = ResourceManager.GetObject("page_40x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAG
        ///	END_TAG
        ///
        ///	PROGRAM MainProgram (MAIN := &quot;MainRoutine&quot;,
        ///	                     MODE := 0,
        ///	                     DisableFlag := 0,
        ///	                     UseAsFolder := 0)
        ///		TAG
        ///		END_TAG
        ///
        ///		ROUTINE MainRoutine 
        ///		END_ROUTINE
        ///
        ///		CHILD_PROGRAMS
        ///		END_CHILD_PROGRAMS
        ///
        ///	END_PROGRAM
        ///
        ///	TASK MainTask (Type := CONTINUOUS,
        ///	               Rate := 10,
        ///	               Priority := 10,
        ///	               Watchdog := 500,
        ///	               DisableUpdateOutputs := No,
        ///	               InhibitTask := No)
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tail {
            get {
                return ResourceManager.GetString("tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tools_40x {
            get {
                object obj = ResourceManager.GetObject("tools_40x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
